---
title: "Computational notebooks to facilitate writing and improve reproducibility of ecological research"
output: word_document
date: "`r format(Sys.time(), '%B %d, %Y')`"
---
<!-- Submission to PLOS biology could fall into one of the two types of articles (no length limit in either case): -->
<!-- - [...] high-quality tutorials (including multimedia presentations) teaching important concepts in the field of computational biology. -->
<!-- - Software articles describing outstanding open source software of exceptional importance that has been shown to provide new biological insights. -->

<!-- The second option would be Ecography, as a "Software note": Software note articles should be maximum 4000 words in length (main text) and maximum 2 figures, tables or boxes. -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- Author information -->
Corresponding author: Ludmilla Figueiredo

E-mail: ludmilla.figueiredo@uni-wuerzburg.de

ORCiD id: https://orcid.org/0000-0001-8217-7800

\doublespace

Juliano Sarmento Cabral

E-mail: juliano.sarmento_cabral@uni-wuerzburg.de

ORCiD id: https://orcid.org/0000-0002-0116-220X
    
\newpage
    
# Abstract

The increasing use of computational work for data generation, storage, and processing, has made the storage of digital documentation crucial to ensure quality of research. Common practice among data scientists, who use such notebooks to produce reports and inform decision making, its application in ecology is still lacking, despite the tasks being similar. We propose that, for a single project, the content of these documentation files actually overlaps with that of classical lab notebooks and that of the scientific manuscript reporting the project. Therefore, to minimize the amount of work required to manage all the files  related to these contents and optimize their production, we present a starter  kit to facilitate the implementation of computational notebooks in the research process, including publication. The kit contains the template of a computational notebook integrated into a simplified research workflow. As tools in this kit, we compare software currently available to produce notebooks for computational work done in R, Python, and Julia. Although intended at beginners, we also present practices that can be gradually implemented to develop a completely digital research workflow. Moreover we show how, besides documentation, computational notebooks also foster the implementation of principles of open science, such as reproducibility, traceability, and knowledge equity. Our hope is that the kit will provide the minimal tools for researchers to adapt their workflow to integrate such practices.


<!-- keywords -->
**keywords:**

# Introduction

As with other disciplines, the call for reproducibility of ecological studies, as well as practical effort to allow it, have been increasing over the years [@borregaard_towards_2016; @mislan_elevating_2016; @culina_low_2020; @powers_open_2019; @hampton_too_2015; @ellison_repeatability_2010].
These efforts usually target the reproducibility of computational work, i.e. the ability to generate the same results by analyzing the same data set with the same code and software used in the original work [@powers_open_2019]. 
In contrast to observations, which might be bound to specific conditions of a system during observation, it is actually possible to assure the reproducibility of computational work [@borregaard_towards_2016; @peng_reproducible_2011?; @mislan_elevating_2016; @ellison_ repeatability_2010; @powers_open_2019]. 
Nonetheless, code information (code itself as well as software version) are still lacking in publications [@culina_low_2020].   

Code in ecology is either analytical or software [@mislan_elevating_2016]. 
We will focus on analytical work, since there are plenty of guidelines for software publication [e.g. @poisot_best_2016?; @white_some_2015] (also include R packages intractions?.

This guide presents the basic principles of open science and should allow ecologists to set up a minimally reproducible workflow for any given project in R, Julia, or Python.
After this first step, there are increasingly automated workflows that could be set up to make this process even easier, and we'll discuss them briefly at the end.

# The starter kit
The starter kit was specifically designed to deliver a word document (.docx), since this is a more traditinoal format and which requires no further training from co-authors that might not want to establish this workflow.
By the way, as long as the main author keeps the workflow, it is not necessary for othes to adhere to it, although it makes the writing and editing process less cumbersome. 

## Getting started

The file `notebook.Rmd` contains the basic sections:

### YAML 

If version control is in place, comments will be done in the .Rmd file, but they could nonetheless be moved from .docx files to the .Rmd by the main author. 

Worst case scenario, where authors want to keep an online version (e.g. Google Drive, Dropbox), the .Rmd file can still be used to generated a comprehensive Supplementary material.

### Headings

## Formatting tables
`kableExtra` to read from tabular formats 

## Presenting results

`.Rmd` can handle Julia and Python.

Others have created tools to adress this issue: @noble_quick_guide

"no Workflow" on Python: check it

R packages on GitHub (published? if not this paper provides a platform for them).

Kitzes, J. and Wilber, M. 2016. macroeco: reproducible ecological pattern analysis in Python. – Ecography 39: 361–367
BUT check that ENM already is a tool to to establish workflows, document and share analytical methods.

Taverna in Booregaard is a tool to design reproducible workflows
Booregaard already provides tools for reproducibility of
different kinds. I should probably present mine is 'ra starter-kit, i. e. the easiest way to start with it and than go there from here as the took in Boregaard (i. e. what I actually proposed to do for this project). @powers-open-2019 talk about the importance of shared workflows
and I'll provide a tool for it.

Booregaard says that script might not be the most friendly, but I can argue that they are if written into a computational notebook form, where the text informs the code.

# Where to go next

In this stater kit, wegave the simplest solutions, to facilitate the transition of researchers with the minimal ammount of friction. Once the practices listed here are set, it should be easier to try more complex workflows, such as:

LateX and pdf

Emacs and org mode

Experiment with the author field (the formats might make sense)

Author, affiliation, keywords, work only work for html ouputs which could be a next step for reports or even full manuscripts to be shared online.

Glossary of open science?

# Discussion

Transparency is essential for trust in scientific work that affect public policies, but one should be mindful about the potential consequences for endangered species, for example, and issues of knowledge equity for the actors involved in the question [@powers_open_2019].

Reinforcement by journals is necessary: possible format suggested by Mislan

# Funding 
LF was supported by a Freies Wissen mentorship grant.

# Supplementary material

Depending on the formatting a publication requires, it might make sense to make use of fields such as `authors`:
```
---
author:
  - John Doe, Institution One
  - Jane Doe, Institution Two
---
```
which renders 
[!][figures/titlepage_authors_sameline.png]

or
```
---
author:
  - John Doe^[Institution One, john@example.org]
  - Jane Doe^[Institution Two, jane@example.org]
---
```
which renders author information as a footnote:
[!][figures/titlepage_authors_footnote.png]