#' Create a folder named 'proj_name' in 'proj_path', as well as create an Rnotebook and an internal file structure inside 'proj_path/proj_name'.
#'
#' @param proj_name a string, the name the folder of the project.
#' @param proj_path a string, the path where the project folder should be created.
#' @param lang a string, the language \"r\" or \"python\", you want to create your notebook in.
#'  It defaults to "r".
#' @details The file structure and notebooks are detailed here \url{https://github.com/FellowsFreiesWissen/computational_notebooks}.
#' @example
#' source("set_kit.R")
#' set_kit("my_project", getwd())
set_kit <- function(proj_name, proj_path, lang = "r"){
  ## Check project path and whether it is empty
  cat("Will create folder ", file.path(proj_path, proj_name), "at and set your working directory there. \n")
  print("Is that correct? Answer yes or no:")
  user_ans = readline()
  if(user_ans == "no"){
    print("Check help('set_kit') to set up your project's location.")
  }
  if(dir.exists(file.path(proj_path, proj_name))){
    print("There already is a folder with this name in this path. Move it or change its name.")
  }else{
    ## Create project in path
    dir.create(file.path(proj_path, proj_name), recursive = TRUE)

    ## Create file structure
    ### first level
    ### main folders of a project
    sapply(c(file.path(proj_path, proj_name, "results"),
             file.path(proj_path, proj_name, "scripts"),
             file.path(proj_path, proj_name, "tests"),
             file.path(proj_path, proj_name, "text"),
             file.path(proj_path, proj_name, "submission")),
           dir.create)
    ### main folders of results
    sapply(file.path(paste(file.path(proj_path, proj_name, "results"),
                           c("data", "figures","tables"),
                           sep = "/")),
           dir.create)
    sapply(file.path(paste(file.path(proj_path, proj_name, "results", "data"),
                           c("raw", "processed", "metadata"),
                           sep = "/")),
           dir.create)
    ### main folders of text
    sapply(file.path(paste(file.path(proj_path, proj_name, "text"),
                           c("supplementary", "references"),
                           sep = "/")),
           dir.create)

    ## Create the README files
    ### main folder
    sink(file.path(proj_path, proj_name, "README.txt"))
    cat("This folder contains the set up for a reproducible workflow as described by https://github.com/FellowsFreiesWissen/computational_notebooks.git\n")
    cat("\n")
    cat("The file structure is organized as such:\n")
    cat("\n")
    cat("projet_name\n")
    cat("|-- README.txt\n")
    cat("|-- main.Rmd\n")
    cat("|-- results\n")
    cat("|   |-- README.txt\n")
    cat("|   |-- data\n")
    cat("|   |   |-- raw\n")
    cat("|   |   |-- processed\n")
    cat("|   |   |-- metadata\n")
    cat("|   |-- figures\n")
    cat("|   |-- tables\n")
    cat("|-- scripts\n")
    cat("|-- tests\n")
    cat("|-- text\n")
    cat("|   |-- README.txt\n")
    cat("|   |-- main.doc\n")
    cat("|   |-- supplementary\n")
    cat("|   |-- references\n")
    cat("|-- submission\n")
    cat("|   |-- README.txt\n")
    cat("|   |-- journal1\n")
    cat("|       |-- first\n")
    cat("|   |-- journal2\n")
    cat("|       |-- first\n")
    cat("|       |-- revisions\n")
    sink()

    ### results folder
    sink(file.path(proj_path, proj_name, "results/README.txt"))
    cat("This folder contains all files of results or their processing, organized in the following subfolders:")
    cat("\n")
    cat("`data/raw`: your raw data files. These should not be protected against any change after the first storage")
    cat("\n")
    cat("`data/processed`: these are files generated by processing the raw data and these are the ones used in the analysis. It can be a copy of the raw data if that is already ready to use. Any processing of the raw data to generate the files here should be documented in the notebook.")
    cat("`data/metadata`: files containing information about the data that will be useful for future users, readers, and reviewers of your data (e.g. description of variables names, units, and values).")
    cat("\n")
    cat("figures: figures resulting from the analysis of results.")
    cat("\n")
    cat("tables: tables resulting from the analysis of results.")
    cat("\n")
    sink()

    ### scripts folder
    sink(file.path(proj_path, proj_name, "scripts/README.txt"))
    cat("This folder contains all code used to process the data, and which, for some reason or another is not included in the notebook because they are too cumbersome or not of upmost relevancy for comprehension.")
    sink()

    ### text folder
    sink(file.path(proj_path, proj_name, "text/README.txt"))
    cat("This folder contains the main text of the manuscript as well as a folder with the supplementary material and one to store references.")
    sink()

    ### submission folder
    sink(file.path(proj_path, proj_name, "submission/README.txt"))
    cat("This folder contains the files specific to journal submissions, e.g. cover letters, submitted versions.")
    sink()

    ## Create the minimal notebook
    sink(file.path(proj_path, proj_name, paste0(proj_name,".Rmd")))
    cat("---")
    cat("\n")
    cat("title: \"Your title here\"")
    cat("\n")
    cat("output:")
    cat("\n")
    cat("  html_document:")
    cat("\n")
    cat("    code_folding: hide")
    cat("\n")
    cat("    toc: true")
    cat("\n")
    cat("  pdf_document: default")
    cat("\n")
    cat("---")
    cat("\n")
    cat("<!-- ----------- VERY MINIMAL INTRO TO RNOTEBOOKS ----------- -->")
    cat("\n\n")
    cat("Feel free to skip this tutorial if you already know the RMarkdown syntax. Also, make sure to delete it once you submit/share your notebook.")
    cat("\n\n")
    cat("This is your notebook. When filling it, you should obey the RMarkdown syntax.")
    cat("\n")
    cat("Text written directly in the file like this one you are reading, with no special markings, is what we call \"narrative\", and will appear without any special formatting when you generate a `.html` or `.pdf` version of this file (click the \"Knit\" button in the  upper-left part of this panel to do it).")
    cat("\n\n")
    cat("<!-- Text can also be commented out of the html file, as this line. -->
")
    cat("\n\n")
    cat("This line includes `inline code`. Inline code is only formatted differently from narrative text, it is not executed.")
    cat("\n\n")
    cat("Blocks of code (also called 'chunks') are marked with back ticks and the language between braces, like this:")
    cat("\n")
    cat(paste("```{", lang, "}", sep = ""))
    cat("\n")
    cat("print(\"This is an example of a code block\")")
    cat("\n")
    cat("```")
    cat("\n\n")
    cat("To execute the code in the chunk and have its results appear bellow it, click the green \"play\" (\"Run\") button within the chunk or place your cursor inside the chunk and press `Ctrl+Shift+Enter`. ")
    cat("\n\n")
    cat("To insert add a chunk, click the `Insert` button on the toolbar (upper-right of this panel) or press `Ctrl+Alt+I`.")
    cat("\n\n")
    cat("Very important, check how to adjust how much of your code and outputs you want to show in your notebook when you convert it to `.html` or `.pdf` [here](https://bookdown.org/yihui/rmarkdown/r-code.html).")
    cat("\n\n")
    cat("<!-- ----------- END OF VERY MINIMAL INTRO TO RNOTEBOOKS ----------- -->")
    cat("\n\n")
    cat(paste("```{", lang, " set-up, include = FALSE}", sep = ""))
    cat("\n")
    cat("# We suggest having a chunk dedicated to variables containing the paths to the folders related to the project.")
    cat("\n")
    cat("# The code in this chunk is not relevant for the reader, and thus is not included in the knitted version (therefore, `include = FALSE`).")
    cat("\n")
    cat("# This is also useful if you are not using the folder structure suggested by this kit, and want to preserve your privacy.")
    cat("\n")
    cat("# Feel free to edit these paths to adapt them to your needs or not use this suggestion at all.")
    cat("\n\n")
    cat("data_dir <- file.path(\"results\", \"data\", \"processed\")  ## Do NOT play with stuff in raw_data. That is your back-up. Work only on `processed`.")
    cat("\n")
    cat("scripts_dir <- file.path(\"scripts\")")
    cat("\n")
    cat("figs_dir <- file.path(\"results\", \"figures\")")
    cat("\n")
    cat("tabs_dir <- file.path(\"results\", \"tables\")")
    cat("\n")
    cat("suppl_dir <- file.path(\"text\", \"supplementary\")")
    cat("\n")
    cat("```")
    cat("\n\n")
    cat("# Read your data")
    cat("\n")
    cat(paste("```{", lang, "}", sep = ""))
    cat("\n")
    cat("# e.g.")
    cat("\n")
    cat("# data <- read.csv(file.path(data_dir, \"your_datasheet_names.csv\") ## replace with the name of the file you want to read in")
    cat("\n")
    cat("```")
    cat("\n\n")
    cat("# Data analysis")
    cat("\n\n")
    cat("## Figure 1")
    cat("\n")
    cat(paste("```{", lang, "}", sep = ""))
    cat("\n")
    cat("# Here, you write the code to create a graph included in the main text")
    cat("\n")
    cat("# To avoid the repetition of having the same figure here as well, either include a line that saves the figure in the figures directory, or include `eval=FALSE` in the chunk options, and the code will not run. In case you choose the latter, be aware that any objects created here will not actually be created when the notebook gets knitted. Only the code for it will be shown.")
    cat("\n")
    cat("```")
    cat("\n\n")
    cat("## Figure S1")
    cat("\n")
    cat(paste("```{", lang, "}", sep = ""))
    cat("\n")
    cat("# Here, write the code to create a graph that is not included in the main text, and thus referred to as Figure S1")
    cat("\n")
    cat("# Contrary to a chunk with a figure from the main text, do not include `eval=FALSE` in the chunk options, because you want the figure created here will not actually be created when the notebook gets knitted. You can still have a line that saves the figure in the figures directory, but make sure that the figure produced also appears in the notebook when the latter gets knitted.")
    cat("\n")
    cat("```")
    cat("\n\n")
    cat("*R version, the OS and attached or loaded packages:*")
    cat("\n")
    cat("<!-- Leave this chunk so people know the software they need to reproduce your work. -->")
    cat("\n")
    cat("```{r}")
    cat("\n")
    cat("sessionInfo()")
    cat("\n")
    cat("```")
    sink()

    #Then you can set wd here
    setwd(file.path(proj_path, proj_name))

    print("Your project is ready to go")
  }
}
